import SwiftUI   // ← needed for Color, DiseaseCondition.color
import PDFKit
import UIKit

class PDFReportGenerator {

    static func generate(entry: ScanEntry, guide: DiseaseGuide) -> Data? {
        let pdfMetaData = [
            kCGPDFContextCreator: "GAIA Lung AI",
            kCGPDFContextAuthor:  "GAIA v1.0",
            kCGPDFContextTitle:   "Lung Analysis Report"
        ]

        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]

        let pageWidth:  CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin:     CGFloat = 48
        let contentWidth = pageWidth - margin * 2

        // ✅ Fix: 'withActions:' → 'format:'
        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight),
            format: format
        )

        let data = renderer.pdfData { ctx in
            // ── Page 1: Cover & Summary ──
            ctx.beginPage()
            var yPos: CGFloat = margin

            // Header banner
            let headerRect = CGRect(x: 0, y: 0, width: pageWidth, height: 130)
            
            let bannerColor = UIColor(entry.condition.color)
            bannerColor.withAlphaComponent(0.9).setFill()
            UIRectFill(headerRect)

            let appAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 28, weight: .black),
                .foregroundColor: UIColor.white
            ]
            "GAIA Lung AI".draw(at: CGPoint(x: margin, y: 32), withAttributes: appAttrs)

            let subAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 13, weight: .medium),
                .foregroundColor: UIColor.white.withAlphaComponent(0.85)
            ]
            "Chest X-Ray Analysis Report  •  Powered by EfficientNet B3"
                .draw(at: CGPoint(x: margin, y: 68), withAttributes: subAttrs)

            let dateStr = DateFormatter.localizedString(from: entry.timestamp,
                                                        dateStyle: .long, timeStyle: .medium)
            dateStr.draw(at: CGPoint(x: margin, y: 90), withAttributes: subAttrs)
            yPos = 150

            // ── Disclaimer ──
            let disclaimerBg = CGRect(x: margin, y: yPos, width: contentWidth, height: 52)
            UIColor(red: 1, green: 0.95, blue: 0.8, alpha: 1).setFill()
            UIBezierPath(roundedRect: disclaimerBg, cornerRadius: 8).fill()
            let disclaimerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10, weight: .semibold),
                .foregroundColor: UIColor(red: 0.7, green: 0.5, blue: 0, alpha: 1)
            ]
            let disclaimer = "⚠️  MEDICAL DISCLAIMER: This report is generated by an AI model trained on approximately 20,000 images and is for informational purposes only. It may contain errors and does NOT replace professional medical diagnosis. Always consult a licensed physician."
            disclaimer.draw(in: CGRect(x: margin + 10, y: yPos + 8, width: contentWidth - 20, height: 36),
                            withAttributes: disclaimerAttrs)
            yPos += 70

            // ── Patient Info ──
            yPos = drawSectionHeader("PATIENT INFORMATION", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            yPos = drawInfoRow("Patient Name", value: entry.patientName.isEmpty ? "Not provided" : entry.patientName, at: yPos, margin: margin, width: contentWidth)
            yPos = drawInfoRow("Age",          value: entry.patientAge.isEmpty  ? "Not provided" : entry.patientAge,  at: yPos, margin: margin, width: contentWidth)
            yPos = drawInfoRow("Gender",       value: entry.patientGender, at: yPos, margin: margin, width: contentWidth)
            yPos = drawInfoRow("Scan Date",    value: dateStr,             at: yPos, margin: margin, width: contentWidth)
            yPos += 16

            // ── Diagnosis Result ──
            yPos = drawSectionHeader("AI DIAGNOSIS RESULT", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            let resultBg = CGRect(x: margin, y: yPos, width: contentWidth, height: 80)
            bannerColor.withAlphaComponent(0.1).setFill()
            UIBezierPath(roundedRect: resultBg, cornerRadius: 12).fill()
            bannerColor.setStroke()
            UIBezierPath(roundedRect: resultBg, cornerRadius: 12).stroke()

            entry.condition.displayName.draw(
                at: CGPoint(x: margin + 20, y: yPos + 15),
                withAttributes: [.font: UIFont.systemFont(ofSize: 24, weight: .black), .foregroundColor: bannerColor]
            )
            "Confidence: \(Int(entry.confidence * 100))%".draw(
                at: CGPoint(x: margin + 20, y: yPos + 50),
                withAttributes: [.font: UIFont.systemFont(ofSize: 14, weight: .semibold), .foregroundColor: UIColor.darkGray]
            )
            yPos += 100

            // ── Probability Breakdown ──
            yPos = drawSectionHeader("PROBABILITY BREAKDOWN", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            for (label, prob) in entry.probabilities.sorted(by: { $0.value > $1.value }) {
                let barBg = CGRect(x: margin, y: yPos, width: contentWidth, height: 28)
                UIColor(white: 0.95, alpha: 1).setFill()
                UIBezierPath(roundedRect: barBg, cornerRadius: 6).fill()

                let barFill = CGRect(x: margin, y: yPos, width: contentWidth * CGFloat(prob), height: 28)
                let condColor = DiseaseCondition(rawValue: label).map { UIColor($0.color) } ?? UIColor.systemBlue
                condColor.withAlphaComponent(0.75).setFill()
                UIBezierPath(roundedRect: barFill, cornerRadius: 6).fill()

                "\(label): \(String(format: "%.1f", prob * 100))%".draw(
                    at: CGPoint(x: margin + 8, y: yPos + 7),
                    withAttributes: [.font: UIFont.systemFont(ofSize: 12, weight: .semibold), .foregroundColor: UIColor.white]
                )
                yPos += 36
            }
            yPos += 16

            // ── AI Overview ──
            yPos = drawSectionHeader("AI ANALYSIS OVERVIEW", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            yPos = drawTextBlock(guide.overview, at: yPos, margin: margin, width: contentWidth)
            yPos += 8
            yPos = drawTextBlock("Model Reasoning: \(guide.aiReasoning)", at: yPos, margin: margin, width: contentWidth)
            yPos += 16

            // ── X-Ray Findings ──
            if yPos > pageHeight - 200 { ctx.beginPage(); yPos = margin }
            yPos = drawSectionHeader("X-RAY FINDINGS", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            for finding in guide.xrayFindings {
                yPos = drawBulletPoint("• \(finding)", at: yPos, margin: margin, width: contentWidth)
            }

            // ── Page 1 footer ──
            drawFooter(pageNumber: 1, at: pageHeight, margin: margin, width: contentWidth, ctx: ctx)

            // ── Page 2 ──
            ctx.beginPage()
            yPos = margin

            // Page 2 header banner
            bannerColor.withAlphaComponent(0.15).setFill()
            UIRectFill(CGRect(x: 0, y: 0, width: pageWidth, height: 64))
            "GAIA Report — Recommendations & Doctor Guide".draw(
                at: CGPoint(x: margin, y: 22),
                withAttributes: [.font: UIFont.systemFont(ofSize: 15, weight: .bold), .foregroundColor: bannerColor]
            )
            yPos = 84

            yPos = drawSectionHeader("IMMEDIATE STEPS TO FOLLOW", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            for (i, step) in guide.immediateSteps.enumerated() {
                yPos = drawBulletPoint("\(i + 1). \(step.title): \(step.description)", at: yPos, margin: margin, width: contentWidth)
            }
            yPos += 16

            yPos = drawSectionHeader("QUESTIONS TO ASK YOUR DOCTOR", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            for q in guide.doctorQuestions {
                yPos = drawBulletPoint("◆ \(q)", at: yPos, margin: margin, width: contentWidth)
            }
            yPos += 16

            if yPos > pageHeight - 200 { ctx.beginPage(); yPos = margin }

            yPos = drawSectionHeader("PRECAUTIONS & HOME CARE", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            for p in guide.precautions {
                yPos = drawBulletPoint("✓ \(p)", at: yPos, margin: margin, width: contentWidth)
            }
            yPos += 16

            yPos = drawSectionHeader("⚠️ EMERGENCY WARNING SIGNS", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
            let warnH = CGFloat(guide.emergencySignals.count) * 22 + 20
            UIColor(red: 1, green: 0.9, blue: 0.9, alpha: 1).setFill()
            UIBezierPath(roundedRect: CGRect(x: margin, y: yPos, width: contentWidth, height: warnH), cornerRadius: 8).fill()
            UIColor.systemRed.withAlphaComponent(0.4).setStroke()
            UIBezierPath(roundedRect: CGRect(x: margin, y: yPos, width: contentWidth, height: warnH), cornerRadius: 8).stroke()
            yPos += 10
            for signal in guide.emergencySignals {
                yPos = drawBulletPoint("🚨 \(signal)", at: yPos, margin: margin + 10, width: contentWidth - 20, color: .systemRed)
            }
            yPos += 16

            if !entry.notes.isEmpty {
                yPos = drawSectionHeader("NOTES", at: yPos, ctx: ctx, width: contentWidth, margin: margin)
                yPos = drawTextBlock(entry.notes, at: yPos, margin: margin, width: contentWidth)
            }

            // ── Page 2 footer ──
            drawFooter(pageNumber: 2, at: pageHeight, margin: margin, width: contentWidth, ctx: ctx)

        }

        return data
    }

    // MARK: ── Drawing Helpers ──

    /// Stamps a thin footer line with page number and branding at the bottom of every page.
    @discardableResult
    private static func drawFooter(pageNumber: Int, at pageHeight: CGFloat,
                                   margin: CGFloat, width: CGFloat,
                                   ctx: UIGraphicsPDFRendererContext) -> CGFloat {
        let footerY: CGFloat = pageHeight - 36
        UIColor(white: 0.85, alpha: 1).setFill()
        UIRectFill(CGRect(x: margin, y: footerY, width: width, height: 0.75))

        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 8.5, weight: .regular),
            .foregroundColor: UIColor(white: 0.55, alpha: 1)
        ]
        "Page \(pageNumber)"
            .draw(at: CGPoint(x: margin + width - 36, y: footerY + 6), withAttributes: footerAttrs)
        return footerY
    }

    @discardableResult
    private static func drawSectionHeader(_ title: String, at y: CGFloat,
                                          ctx: UIGraphicsPDFRendererContext,
                                          width: CGFloat, margin: CGFloat) -> CGFloat {
        let blue = UIColor(red: 0.2, green: 0.4, blue: 0.8, alpha: 1)
        title.draw(at: CGPoint(x: margin, y: y),
                   withAttributes: [.font: UIFont.systemFont(ofSize: 11, weight: .black), .foregroundColor: blue])
        blue.withAlphaComponent(0.4).setFill()
        UIRectFill(CGRect(x: margin, y: y + 16, width: width, height: 1.5))
        return y + 26
    }

    @discardableResult
    private static func drawInfoRow(_ label: String, value: String, at y: CGFloat,
                                    margin: CGFloat, width: CGFloat) -> CGFloat {
        label.draw(at: CGPoint(x: margin, y: y),
                   withAttributes: [.font: UIFont.systemFont(ofSize: 11, weight: .semibold), .foregroundColor: UIColor.gray])
        value.draw(at: CGPoint(x: margin + 160, y: y),
                   withAttributes: [.font: UIFont.systemFont(ofSize: 11), .foregroundColor: UIColor.black])
        return y + 18
    }

    @discardableResult
    private static func drawTextBlock(_ text: String, at y: CGFloat,
                                      margin: CGFloat, width: CGFloat) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11), .foregroundColor: UIColor.darkGray
        ]
        (text as NSString).draw(in: CGRect(x: margin, y: y, width: width, height: 200), withAttributes: attrs)
        let size = (text as NSString).boundingRect(with: CGSize(width: width, height: 1000),
                                                    options: .usesLineFragmentOrigin,
                                                    attributes: attrs, context: nil)
        return y + size.height + 6
    }

    @discardableResult
    private static func drawBulletPoint(_ text: String, at y: CGFloat,
                                        margin: CGFloat, width: CGFloat,
                                        color: UIColor = .darkGray) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 10.5), .foregroundColor: color]
        (text as NSString).draw(in: CGRect(x: margin, y: y, width: width, height: 100), withAttributes: attrs)
        let size = (text as NSString).boundingRect(with: CGSize(width: width, height: 500),
                                                    options: .usesLineFragmentOrigin,
                                                    attributes: attrs, context: nil)
        return y + size.height + 4
    }
}

//  DiseaseCondition.color is defined in ScanResult.swift
//          Color.uiColor is NOT needed — use UIColor(swiftUIColor) directly
